# Generated by Django 3.2.9 on 2021-12-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default=None, max_length=15)),
                ('address', models.TextField(default=None, max_length=100)),
            ],
        ),
    ]
